name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: dotnet publish
      run: | dotnet publish -c Release -o az2test
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    # Deploy to App Service
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with:
        app-name: az2test1 # Replace with your app name
        publish-profile: ${{ secrets.PUBLISH_PROFILE }} # Replace with the name of your publish profile
        package: './az2test'  # Specify the folder or file to deploy

